### ISSUE TITLE
Failed to create Rabbit MQ channel - Exception Thrown when using Java openjdk 1.8.0_292

### ISSUE THREAD

**Issue by freddiedfre** [sportradar/UnifiedOddsSdkJava#15]
I believe there is a security update in openjdk 1.8.0_292 that causes the following exception to be thrown. Kindly advice on how to go about this. 

Thanks

![Screenshot from 2021-05-15 05-38-31](https://user-images.githubusercontent.com/4942663/118345879-411ebd00-b540-11eb-93e8-0b9dd6c63376.png)

**Comment by freddiedfre** [comment]
The tempory solution i've used is commenting out the jdk.jar.disabledAlgorithms settings in my java jdk security.policy

**Comment by dhrovat** [comment]
Latest version was updated to try connecting with TLSv1.2, which should resolve the issue.
