### ISSUE TITLE
The log level not working at all

### ISSUE THREAD

**Issue by hotyes** [sportradar/UnifiedOddsSdkJava#19]
Hi there, I have try to configure the log level to any logger. But the raw message is always print out on the console.  I have set the log level to 'error' for the following 

- com.sportradar
- com.sportradar.unifiedodds.sdk.LoggerDefinitions$UFSdkTrafficLog
- com.sportradar.unifiedodds.sdk.LoggerDefinitions$UFSdkTrafficFailureLog
- com.sportradar.unifiedodds.sdk.LoggerDefinitions$UFSdkRestTrafficLog
- com.sportradar.unifiedodds.sdk.LoggerDefinitions$UFSdkClientInteractionLog
 

using log4j2.xml

any idea?

**Comment by dhrovat** [comment]
Hi,
the raw message body is logged under com.sportradar.unifiedodds.sdk.LoggerDefinitions$UFSdkTrafficLog. The other way it might be that you log it in onRawFeedMessageReceived method in your listener; would suggest checking that also.
For more details would need insight into your configs for loggers, and perhaps even logs.
