### ISSUE TITLE
After successful reconnect after connection loss due to 100% packet drop rate the radar client started printing ERROR messages and stopped dispatching events 

### ISSUE THREAD

**Issue by thormoz** [sportradar/UnifiedOddsSdkJava#21]
After few days of uptime and normal work we started seeing ERROR messages containing XML strings. 
We have no way to intercept and handle it. 
Note: The only thing we do in MessageListenerImpl events is to take and move these messages in internal queues. 

Attaching file with what we observe coming from the client.
[radar_java_client.txt](https://github.com/sportradar/UnifiedOddsSdkJava/files/7704053/radar_java_client.txt)

**Comment by thormoz** [comment]
After short investigation on our side we found out that the SDK has problems parsing a certain message and dispatches UnparsableMessage event.
The unparsable messages are the logged xmls in the example above. 

So now the question is how out of the blue the SDK starts receiving messages which are unparsable and how we should handle these cases?  (Restarting helped but this is highly not recommended solution in my opinion.)

**Comment by thormoz** [comment]
Today we reproduced it or atleast saw exactly when this happens.

We received conneciton close message, because there was 100% packet loss. 

After the connection was up and the client reconnected it started sending unparsable messages.

It seems there is some problem with the client reconnect functionality.

**Comment by dhrovat** [comment]
Thank you for finding this out. It was fixed and will be available in next release.
