### ISSUE TITLE
Radar's Java client 2.0.52.1 receives duplicated messages

### ISSUE THREAD

**Issue by thormoz** [sportradar/UnifiedOddsSdkJava#23]
It works sporadically. Sometimes it works normal and receives 1 OC, sometimes 2 and sometimes 5 or more.

Attaching SDK logs and the way the client is configured.
![image](https://user-images.githubusercontent.com/11569577/152944030-a09b9cc8-2649-4ce8-82a7-814d4f22c1c5.png)
![image](https://user-images.githubusercontent.com/11569577/152943829-0b2ee558-f392-47d1-87a0-89e3924d4b47.png)

[dupped_messages.csv](https://github.com/sportradar/UnifiedOddsSdkJava/files/8021848/dupped_messages.csv)

**Comment by dhrovat** [comment]
Hi,
this is most likely linked to issue when disconnection happens, sdk may create multiple connections (previous one is not closed properly). This was resolved in latest version.
Please update and retry.
